import json
import mimetypes
import os
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

PUBLIC_PURPOSES = ("REQUEST_PHOTO", "PARTNER_PROFILE_PHOTO", "SERVICE_ICON")


class LocalStorage:
    def __init__(self, cfg):
        """Keep the two roots for local file storage.
        Public images are served over HTTP; private ones never are.
        Identity documents and selfies always go to the private root."""
        self.public_root = Path(cfg.media_public_root)
        self.private_root = Path(cfg.media_private_root)
        self.public_base_url = cfg.media_public_base_url.rstrip("/")

    def _path(self, purpose, key):
        """Resolve where a stored object lives on disk.
        The purpose decides between the public and private root.
        Keys are generated by us and never contain '..'."""
        root = self.public_root if purpose in PUBLIC_PURPOSES else self.private_root
        return root / key

    def save(self, purpose, key, data):
        """Write an uploaded image to disk.
        Returns the public URL, or None for private purposes.
        Raises OSError when the disk refuses."""
        path = self._path(purpose, key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return f"{self.public_base_url}/{key}" if purpose in PUBLIC_PURPOSES else None

    def delete(self, purpose, key):
        """Remove a stored image from disk.
        A file that is already gone is not an error.
        Used when an identity check is decided."""
        path = self._path(purpose, key)
        if path.exists():
            os.remove(path)

    def read(self, purpose, key):
        """Return a stored image's bytes, or None when it is gone.
        Used by the admin console to show identity images."""
        path = self._path(purpose, key)
        return path.read_bytes() if path.is_file() else None


class SupabaseStorage:
    """Images in Supabase Storage: public purposes in one public bucket, the rest in a private one.
    Every failure is an OSError, so callers handle it the way they handle a full disk."""

    _ensured = set()

    def __init__(self, cfg):
        """Read the project URL, secret key and bucket names.
        Refuses to start without the URL and key.
        The key is a server secret and only ever sent to Supabase."""
        if not (cfg.supabase_url and cfg.supabase_service_role_key):
            raise RuntimeError("STORAGE_BACKEND=supabase needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY")
        self.base = cfg.supabase_url.rstrip("/")
        self.key = cfg.supabase_service_role_key
        self.public_bucket = cfg.supabase_public_bucket
        self.private_bucket = cfg.supabase_private_bucket
        self.timeout = 15

    def _bucket(self, purpose):
        """Pick the bucket for a purpose.
        Public purposes are served by URL; everything else needs the secret key."""
        return self.public_bucket if purpose in PUBLIC_PURPOSES else self.private_bucket

    def _call(self, method, path, data=None, content_type="application/json"):
        """Send one request to the Storage API and return (status, body bytes).
        Legacy JWT keys also go in Authorization; new secret keys use apikey alone.
        Network errors raise OSError; HTTP errors are returned for the caller to judge."""
        headers = {"apikey": self.key, "Content-Type": content_type}
        if self.key.startswith("eyJ"):
            headers["Authorization"] = f"Bearer {self.key}"
        req = urllib.request.Request(f"{self.base}/storage/v1/{path}", data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                return resp.status, resp.read()
        except urllib.error.HTTPError as exc:
            return exc.code, exc.read()

    def _ensure_bucket(self, name, public):
        """Create a bucket the first time it is needed in this process.
        A bucket that already exists is fine. Anything else is an OSError."""
        if name in self._ensured:
            return
        status, body = self._call("POST", "bucket", json.dumps({"id": name, "name": name, "public": public}).encode())
        if status >= 300 and b"already exists" not in body.lower() and status != 409:
            raise OSError(f"could not create bucket {name}: {status} {body[:200]!r}")
        self._ensured.add(name)

    def save(self, purpose, key, data):
        """Upload one image and return its public URL, or None for private purposes.
        Buckets are created on first use. Raises OSError when Supabase refuses."""
        bucket = self._bucket(purpose)
        self._ensure_bucket(bucket, purpose in PUBLIC_PURPOSES)
        content_type = mimetypes.guess_type(key)[0] or "application/octet-stream"
        status, body = self._call("POST", f"object/{bucket}/{urllib.parse.quote(key)}", data, content_type)
        if status >= 300:
            raise OSError(f"upload of {key} failed: {status} {body[:200]!r}")
        return f"{self.base}/storage/v1/object/public/{bucket}/{key}" if purpose in PUBLIC_PURPOSES else None

    def delete(self, purpose, key):
        """Remove one image. One that is already gone is not an error."""
        status, body = self._call("DELETE", f"object/{self._bucket(purpose)}/{urllib.parse.quote(key)}")
        if status >= 300 and status != 404:
            raise OSError(f"delete of {key} failed: {status} {body[:200]!r}")

    def read(self, purpose, key):
        """Return a stored image's bytes, or None when it is gone.
        Reads with the secret key, so it works for private buckets."""
        status, body = self._call("GET", f"object/authenticated/{self._bucket(purpose)}/{urllib.parse.quote(key)}")
        if status in (400, 404):
            return None
        if status >= 300:
            raise OSError(f"read of {key} failed: {status} {body[:200]!r}")
        return body


def storage(cfg):
    """Pick the storage backend from configuration.
    STORAGE_BACKEND is local (disk) or supabase (Supabase Storage)."""
    if cfg.storage_backend == "local":
        return LocalStorage(cfg)
    if cfg.storage_backend == "supabase":
        return SupabaseStorage(cfg)
    raise RuntimeError(f"unknown STORAGE_BACKEND {cfg.storage_backend}")
